config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index', as: :welcome
  # Authentication Paths
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/register', to: 'users#new', as: :registration
  post '/register', to: 'users#create'
  # navigation bar paths
  get '/resume', to: 'resume_items#index', as: :resume
  resources :blog_posts
  # get '/blog', to: 'blog_posts#index'
  # get '/blog/:id', to: 'blog_posts#show'

  resources :users, only: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_many :user_posts
  has_many :users, through: :user_posts
  has_many :resources
  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :published

  def self.get_all
    select(:id, :title, :summary, :published)
    .order(published: :desc)
  end
end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :blog_post
  validates_presence_of :name
end

app/models/resume_item.rb
class ResumeItem < ApplicationRecord
  validates_presence_of :category
  validates_presence_of :title

  def self.summary
    select(:title, :description)
    .where(active: true)
    .where(category: "Summary")
  end

  def self.education
    select(:title, :description)
    .where(active: true)
    .where(category: "Education")
  end

  def self.experience
    select(:title, :description)
    .where(active: true)
    .where(category: "Experience")
  end

  def self.projects
    select(:title, :description, :source_code, :production_site)
    .where(active: true)
    .where(category: "Projects")
  end

  def self.skills
    select(:description)
    .where(active: true)
    .where(category: "Skills")
    .order(:description)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_posts
  has_many :blog_posts, through: :user_posts
  validates_presence_of :first_name
  validates_presence_of :last_name
end

app/models/user_post.rb
class UserPost < ApplicationRecord
  belongs_to :user
  belongs_to :blog_post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ActionView::Helpers::TextHelper

  helper_method :current_user, :current_admin?, :current_reguser?

  def cart
    @cart ||= Cart.new(session[:cart])
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def current_reguser?
    current_user && current_user.default?
  end

  def visitor_or_user
    render file: 'public/404', status: 404 unless current_user.nil? || current_reguser?
  end

  def require_reguser
    render file: 'public/404', status: 404 unless current_reguser?
  end

  def require_admin
    render file: 'public/404', status: 404 unless current_admin?
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.get_all
  end

  def show
    @blog_post = BlogPost.find(params["id"].to_i)
    @blog_posts = BlogPost.get_all
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      flash[:success] = "Your post has been saved!"
      redirect_to blog_posts_path
    else
      flash[:danger] = @blog_post.errors.full_messages
      render :new
    end
  end

  def edit
    @blog_posts = BlogPost.find_by(slug: params[:slug])
  end

  def update
    if blog_posts_params[:slug]
      @blog_posts = BlogPost.find_by(slug: blog_posts_params[:slug])
    else
      @blog_posts = BlogPost.find_by(slug: params[:slug])
    end
    if @blog_posts.update(blog_posts_params)
      flash[:success] = "Your BlogPost has been updated!"
      redirect_to dashboard_blog_posts_path
    else
      flash[:danger] = @blog_posts.errors.full_messages
      @blog_posts = BlogPost.find_by(id: params[:id])
      render :edit
    end
  end

  private
  def blog_post_params
    params.require(:blog_post).permit(:title, :summary, :content, :published)
  end
end

app/controllers/resume_items_controller.rb
class ResumeItemsController < ApplicationController
  def index
    @user = User.find_by_last_name("Stiehl")
    @summary = ResumeItem.summary
    @education = ResumeItem.education
    @experience = ResumeItem.experience
    @skills = ResumeItem.skills
    @projects = ResumeItem.projects
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for @blog_post do |f| %>
<!--  form_for @item, url: dashboard_item_path(@item) do |f| -->
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :summary %>
    <%= f.text_field :summary %>
  </p>

  <p>
    <%= f.label :content %>
    <%= f.text_field :content %>
  </p>

  <p>
    <%= f.label :published %>
    <%= f.date_field :published %>
  </p>

  <%= f.submit %>
<% end %>

app/views/blog_posts/edit.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-12">
      <div class="card" >
        <div class="card-header">Edit blog post</div>
          <div class="card-body">
            <%= render partial: "form", method: :patch %>
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/blog_posts/index.html.erb
<h1>Blog Posts</h1>
<% BlogPost.get_all.each do |blog_post| %>
<div class="card" style="width: 72rem;">
  <div class="card-body">
    <h5 class="card-title"><%= link_to blog_post.title, blog_post_path(id: blog_post) %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= blog_post.published %></h6>
    <p class="card-text"><%= blog_post.summary %></p>
    </div>
  </div>
  <% end %>
  <div class="add">
    <%= link_to "Add a post", new_blog_post_path %>
  </div>

app/views/blog_posts/new.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-12">
      <div class="card" >
        <div class="card-header">New blog post</div>
          <div class="card-body">
            <%= render partial: "form" %>
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/blog_posts/show.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-7">
      <div class="card" >
        <div class="card-header"><%= @blog_post.title %>  || <%= @blog_post.published %></div>
          <div class="card-body">
            <p><%= @blog_post.summary %></p>
            <p><%= @blog_post.content %></p>
          </div>
        </div>
      </div>

      <div class="col-4">
        <div class="card">
          <div class="card-header">All Posts</div>
          <% @blog_posts.each do |blog_post| %>
          <div class="card-body">
              <li class="card-text"> <%= link_to blog_post.title, blog_post_path(id: blog_post)  %></li>
            </div>
            <% end %>
          </div>
        </div>

    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <%= link_to "Home", '/' %>
        <%= link_to "Resume", '/resume' %>
        <%= link_to "Blog", '/blog_posts' %>

        <!-- < if current_user >
          <= link_to "Log out", logout_path > <!--, method: :delete >
        < else >
          <= link_to "Register as a User", new_user_path >
          <= link_to "Login", login_path >
        < end >
      -->
      </nav>
      <div class="container" id="body-content-no-nav">
      <% flash.each do |flash_type, flash_message| %>
        <% if flash_message.class == Array %>
          <% flash_message.each do |single_message| %>
            <div class="alert alert-<%= flash_type %>" role="alert"><%= single_message %></div>
          <% end %>
        <% else %>
          <div class="alert alert-<%= flash_type %>" role="alert"><%= flash_message %></div>
        <% end %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/resume_items/index.html.erb
<div class="container-fluid">
  <h1> <%= @user.first_name  %> <%= @user.last_name  %> </h1>
  <div class="row">
  <div class="col-7">

  <div class="card" >
    <div class="card-header">Summary</div>
      <div class="card-body">
        <% @summary.each do |resume_item| %>
          <p class="card-text"><%= resume_item.description %></p>
        </div>
      </div>
      <% end %>
      <div class="card">
        <div class="card-header">Projects</div>
        <div class="card-body">
          <% @projects.each do |resume_item| %>
          <h6 class="card-subtitle"><%= resume_item.title %></h6>
          <p class="card-text"><%= resume_item.description %></p>
          <p><%= resume_item.source_code %> | <%= resume_item.production_site %></p>
          <% end %>
        </div>
      </div>

      <div class="card">
        <div class="card-header">Experience</div>
        <div class="card-body">
          <% @experience.each do |resume_item| %>
            <h6 class="card-subtitle"><%= resume_item.title %></h6>
              <p class="card-text"><%= resume_item.description %></p>
          <% end %>
        </div>
      </div>
    </div>

<div class="col-5">
  <div class="card">
    <div class="card-header">Contact</div>
    <div class="card-body">
        <li class="card-text"><%= link_to nil, @user.linkedin_profile %></li>
        <li class="card-text"><%= link_to nil, @user.github_handle %></li>
        <li class="card-text"><%= link_to nil, @user.twitter_handle %></li>
        <li class="card-text"><%= @user.email %></li>
        <li class="card-text"><%= number_to_phone(@user.phone) %></li>
        <li class="card-text"><%= @user.location %></li>
    </div>
  </div>

    <div class="card">
      <div class="card-header">Skills</div>
      <div class="card-body">
        <% @skills.each do |resume_item| %>
          <li class="card-text"><%= resume_item.description %></li>
        <% end %>
      </div>
    </div>
    <div class="card">
      <div class="card-header">Education</div>
        <div class="card-body">
            <% @education.each do |resume_item| %>
              <h6 class="card-subtitle"><%= resume_item.title %></h6>
                <p class="card-text"><%= resume_item.description %></p>
              <% end %>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome</h1>